steps:

  - label: ":pulumi: Preview"
    if: build.pull_request.id != null
    command: |
      export PULUMI_ACCESS_TOKEN="$$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"
      pulumi install
      pulumi stack select dev
      pulumi preview

  - label: ":pulumi: Deploy"
    if: build.branch == "main" && build.pull_request.id == null
    command: |
      export PULUMI_ACCESS_TOKEN="$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"
      pulumi install
      pulumi stack select dev
      pulumi up -y
      
      CDN_URL="https://$$(pulumi stack output distributionDomainName)"
      echo ":white_check_mark: CloudFront URL: [$CDN_URL]($CDN_URL)" | buildkite-agent annotate --style "success"
    